/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-web:2.2.0.RELEASE")
    api("org.springframework.kafka:spring-kafka:2.3.1.RELEASE")
    api("org.projectlombok:lombok:1.18.10")
    api("com.google.code.gson:gson:2.8.6")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.2.0.RELEASE")
    testImplementation("org.springframework.kafka:spring-kafka-test:2.3.1.RELEASE")
}

group = "com.asb.example"
version = "0.0.1-SNAPSHOT"
description = "spring-kafka-producer-example"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
